"""empty message

Revision ID: 687c94017934
Revises: ae5a07fbe299
Create Date: 2025-03-20 20:15:28.319629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687c94017934'
down_revision: Union[str, None] = 'ae5a07fbe299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('image_url', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'image_url')
    # ### end Alembic commands ###
