"""end db

Revision ID: 8bf714679e37
Revises: 2b67b3592374
Create Date: 2025-04-14 10:02:07.870124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf714679e37'
down_revision: Union[str, None] = '2b67b3592374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('PhotoURL', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'PhotoURL')
    # ### end Alembic commands ###
