"""empty message

Revision ID: ae5a07fbe299
Revises: edf879cdfb18
Create Date: 2025-03-20 20:13:25.404208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5a07fbe299'
down_revision: Union[str, None] = 'edf879cdfb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('PlatformID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Events', 'Platforms', ['PlatformID'], ['PlatformID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.drop_column('Events', 'PlatformID')
    # ### end Alembic commands ###
