"""empty message

Revision ID: beae7758e660
Revises: 687c94017934
Create Date: 2025-03-20 20:17:33.742798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beae7758e660'
down_revision: Union[str, None] = '687c94017934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('image_url', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
