"""empty message

Revision ID: edf879cdfb18
Revises: 
Create Date: 2025-03-20 20:10:27.474197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf879cdfb18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Platforms',
    sa.Column('PlatformID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('City', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Image', sa.String(length=255), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('PlatformID')
    )
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Login', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=256), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Surname', sa.String(length=255), nullable=True),
    sa.Column('Patronymic', sa.String(length=255), nullable=True),
    sa.Column('City', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Login')
    )
    op.create_table('Events',
    sa.Column('EventID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('City', sa.String(length=255), nullable=True),
    sa.Column('DateStart', sa.DateTime(), nullable=True),
    sa.Column('DateEnd', sa.DateTime(), nullable=True),
    sa.Column('TimeStart', sa.Time(), nullable=True),
    sa.Column('TimeEnd', sa.Time(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('EventID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    op.drop_table('Users')
    op.drop_table('Platforms')
    # ### end Alembic commands ###
